!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - clip_range
    - 0.1
  - - ent_coef
    - 0.00017657328245977743
  - - gae_lambda
    - 0.92
  - - gamma
    - 0.9999
  - - learning_rate
    - lin_0.0004949476702088278
  - - max_grad_norm
    - 0.9
  - - n_envs
    - 8
  - - n_epochs
    - 10
  - - n_steps
    - 2048
  - - n_timesteps
    - 100000000.0
  - - policy
    - MultiInputPolicy
  - - policy_kwargs
    - dict(log_std_init=-2, ortho_init=False, activation_fn=nn.ReLU, net_arch=[dict(pi=[512,
      512, 256], vf=[512, 512, 256])])
  - - sde_sample_freq
    - 4
  - - use_sde
    - false
  - - vf_coef
    - 0.9744573198968881
