!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 256
  - - clip_range
    - 0.2
  - - ent_coef
    - 0.03236081644151682
  - - gae_lambda
    - 0.9
  - - gamma
    - 0.9999
  - - learning_rate
    - 0.0003785153719552746
  - - max_grad_norm
    - 0.5
  - - n_envs
    - 8
  - - n_epochs
    - 10
  - - n_steps
    - 32
  - - n_timesteps
    - 100000000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict(log_std_init=-2, ortho_init=False, activation_fn=nn.LeakyReLU, net_arch=[dict(pi=[64,
      64, 32, 32], vf=[64, 64, 32, 32])])
  - - sde_sample_freq
    - 4
  - - use_sde
    - false
  - - vf_coef
    - 0.7625576703936189
